<a href="https://colab.research.google.com/github/ak424/smartknower/blob/master/Spam_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [6]:
df=pd.read_csv('/content/drive/My Drive/python/emails.csv')

In [37]:
df

Email No.  the  to  ect  and  ...  military  allowing  ff  dry  Prediction
0        Email 1    0   0    1    0  ...         0         0   0    0           0
1        Email 2    8  13   24    6  ...         0         0   1    0           0
2        Email 3    0   0    1    0  ...         0         0   0    0           0
3        Email 4    0   5   22    0  ...         0         0   0    0           0
4        Email 5    7   6   17    1  ...         0         0   1    0           0
...          ...  ...  ..  ...  ...  ...       ...       ...  ..  ...         ...
5167  Email 5168    2   2    2    3  ...         0         0   0    0           0
5168  Email 5169   35  27   11    2  ...         0         0   1    0           0
5169  Email 5170    0   0    1    1  ...         0         0   0    0           1
5170  Email 5171    2   7    1    0  ...         0         0   1    0           1
5171  Email 5172   22  24    5    1  ...         0         0   0    0           0

[5172 rows x 3002 columns]

In [7]:
df.shape

(5172, 3002)

In [8]:
x = df.iloc[:,2:3001].values
y = df.iloc[:,3001].values

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, random_state = 0)

In [10]:
from sklearn.neighbors import KNeighborsClassifier



In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [16]:
model = KNeighborsClassifier(n_neighbors=5)

In [19]:
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [56]:
y_pred


array([1, 0, 0, ..., 1, 0, 1])

In [20]:

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

86.77494199535964

In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[780, 149],
       [ 22, 342]])

In [29]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.84      0.90       929
           1       0.70      0.94      0.80       364

    accuracy                           0.87      1293
   macro avg       0.83      0.89      0.85      1293
weighted avg       0.89      0.87      0.87      1293



In [53]:
#SUPPORT VECTOR MACHINE

In [1]:
from sklearn.svm import SVC

In [2]:
model2=SVC()


In [13]:
model2.fit(x_train,y_train)
y_pre=model2.predict(x_test)

In [23]:
accuracy_score(y_pre,y_test)*100

93.96751740139212

In [24]:
confusion_matrix(y_pre,y_test)

array([[920,  69],
       [  9, 295]])

In [27]:
print(classification_report(y_pre,y_test))

              precision    recall  f1-score   support

           0       0.99      0.93      0.96       989
           1       0.81      0.97      0.88       304

    accuracy                           0.94      1293
   macro avg       0.90      0.95      0.92      1293
weighted avg       0.95      0.94      0.94      1293

